jenkins:
  image: blacklabelops/jenkins
  ports:
   - "8090:8080"
  volumes:
   - /jenkins
  environment:
    - 'JENKINS_ADMIN_USER=jenkins'
    - 'JENKINS_ADMIN_PASSWORD=swordfish'
    - 'JAVA_VM_PARAMETERS=-Xmx512m -Xms256m'
    - 'JENKINS_MASTER_EXECUTORS=2'
    - 'JENKINS_PLUGINS=swarm git'
