jenkins:
  image: blacklabelops/jenkins
  ports:
   - "8090:8080"
  volumes:
   - /jenkins
  environment:
     - 'JAVA_VM_PARAMETERS=-Xmx512m'
     - 'JENKINS_MASTER_EXECUTORS=2'
     - 'JENKINS_PLUGINS=swarm'
